import { TimepointModel } from "./model/TimepointModel";

export const timepoints: TimepointModel[] = [
  {
    _id: 1,
    title: "Spanien",
    content: "Lorem nt ut labore e erat, sed diam voluptua. At vero eos e",
    picture: "url",
    date: "25.03.2019",
    type: "Beruflich",
    visible: true,
    userId: "234234234j23jk42k3j",
  },
  {
    _id: 2,
    title: "Russland",
    content: "Lorem nt ut labore e erat, sed diam voluptua. At vero eos e Lorem nt ut labore e erat, sed diam voluptua. At vero eos e",
    picture: "url",
    date: "25.03.2019",
    type: "Urlaub",
    visible: true,
    userId: "234234234j23jk42k3j",
  },
  {
    _id: 3,
    title: "Deutschland",
    content: "TRet das und das",
    picture: "url",
    date: "25.03.2019",
    type: "Beruflich",
    visible: true,
    userId: "234234234j23jk42k3j",
  },
  {
    _id: 4,
    title: "Spanien",
    content: "Lorem nt ut labore e erat, sed diam voluptua. At vero eos e Lorem nt ut labore e erat, s",
    picture: "url",
    date: "25.03.2019",
    type: "Beruflich",
    visible: true,
    userId: "234234234j23jk42k3j",
  },
  {
    _id: 5,
    title: "Spanien",
    content: "TRet Lorem nt ut labore e erat, sed diam voluptua. At vero eos e Lorem nt ut labore e erat, s",
    picture: "url",
    date: "25.03.2019",
    type: "Urlaub",
    visible: true,
    userId: "234234234j23jk42k3j",
  },
  {
    _id: 6,
    title: "Spanien",
    content: "Lorem nt ut labore e erat, sed diam voluptua. At vero eos e Lorem nt ut labore e erat, s",
    picture: "url",
    date: "25.03.2019",
    type: "Beruflich",
    visible: true,
    userId: "234234234j23jk42k3j",
  },
];
